# syntax=docker/dockerfile:1.7.0

FROM rust:1.81.0-slim-bookworm as base

RUN cargo install cargo-chef --version ^0.1

FROM base AS planner

WORKDIR /app

COPY . .

RUN cargo chef prepare --recipe-path recipe.json



FROM base as builder

WORKDIR /app

COPY --from=planner /app/recipe.json recipe.json

RUN cargo chef cook --release --recipe-path recipe.json

COPY . .

RUN cargo build
